FROM node:10-alpine

ARG NODE_ENV=development
ENV NODE_ENV NODE_ENV

ENV DIR /usr/src

WORKDIR ${DIR}/api
COPY ./lib ${DIR}/lib

COPY ./api .

# Install python as we need it to compile native dependencies with no prebuilt binaries
RUN apk --no-cache add --virtual builds-deps build-base python
RUN yarn install

RUN yarn run build src

CMD yarn run serve